---
Name: silverstripe-forager-opensearch
Only:
  envvarset: 'OPENSEARCH_ENDPOINT'
After:
  - 'silverstripe-forager'
  - 'search-forager-default'
---

SilverStripe\Core\Injector\Injector:
  SilverStripe\Forager\Service\IndexConfiguration:
    constructor:
      index_variant: '`OPENSEARCH_INDEX_VARIANT`'

  SilverStripe\Forager\Interfaces\IndexingInterface:
    class: Somar\ForagerElasticsearch\Service\OpensearchService
    constructor:
      client: '%$OpenSearch\Client.managementClient'
      configuration: '%$SilverStripe\Forager\Service\IndexConfiguration'
      builder: '%$SilverStripe\Forager\Service\DocumentBuilder'

  OpenSearch\Client.managementClient:
    factory: Somar\ForagerElasticsearch\Service\ClientFactory
    constructor:
      endpoint: '`OPENSEARCH_ENDPOINT`'
      username: '`OPENSEARCH_USERNAME`'
      password: '`OPENSEARCH_PASSWORD`'
      aws_service: '`OPENSEARCH_AWS_SERVICE`'
      aws_region: '`OPENSEARCH_AWS_REGION`'

# // analysis is the top-level OpenSearch settings key where analyzers, tokenizers, char filters, and token filters are configured
Somar\ForagerElasticsearch\Service\OpensearchService:
  settings_requiring_closed_index:
    - analysis

SilverStripe\Forager\DataObject\DataObjectDocument:
  id_field: record_id
  base_class_field: record_base_class
  page_content_field: page_content
